"""Realistic mock data simulating Microsoft Hyper-V / SCVMM API responses.

5 VMs with checkpoints, replication, SCVMM integration, virtual switches,
VHD/VHDX disks.
"""

HYPERV_MOCK_DATA: dict = {
    "virtual_machines": [
        {
            "vm_id": "hv-vm-3001",
            "name": "DC-PROD-01",
            "guid": "c8f12a3b-4d5e-6f78-9a01-b2c3d4e5f601",
            "state": "Running",
            "generation": 2,
            "os": {
                "name": "Windows Server",
                "version": "2022 Datacenter",
                "reference_code": "WIN_SVR_2022_64",
            },
            "cpu": {
                "count": 4,
                "reservation_mhz": 0,
                "limit_mhz": 100000,
                "relative_weight": 100,
            },
            "memory": {
                "startup_mb": 8192,
                "dynamic_enabled": True,
                "minimum_mb": 4096,
                "maximum_mb": 16384,
                "buffer_percentage": 20,
            },
            "disks": [
                {
                    "name": "DC-PROD-01-OS.vhdx",
                    "path": "C:\\ClusterStorage\\Vol1\\DC-PROD-01\\DC-PROD-01-OS.vhdx",
                    "format": "VHDX",
                    "type": "Dynamic",
                    "max_size_gb": 127,
                    "current_size_gb": 45,
                    "controller": "SCSI Controller 0",
                },
            ],
            "network_adapters": [
                {
                    "name": "Corp-NIC",
                    "switch_name": "vSwitch-Corp",
                    "vlan_id": 10,
                    "mac_address": "00:15:5D:01:01:01",
                    "ip_address": "172.16.10.11",
                    "connected": True,
                },
            ],
            "checkpoints": [
                {
                    "name": "Pre-Patch-2026-03",
                    "created_at": "2026-03-15T02:00:00Z",
                    "type": "Production",
                    "size_gb": 8.5,
                },
            ],
            "replication": {
                "enabled": True,
                "mode": "Primary",
                "replica_server": "HV-REPLICA-01.corp.local",
                "frequency_seconds": 300,
                "state": "Replicating",
            },
            "cluster": {
                "name": "HV-Cluster-Prod",
                "node": "HV-NODE-01.corp.local",
                "highly_available": True,
            },
            "scvmm": {
                "cloud": "Production-Cloud",
                "service_template": "DC-Template-v2",
                "custom_properties": {
                    "CostCenter": "IT-OPS-001",
                    "Owner": "infrastructure-team",
                },
            },
            "tags": {"env": "production", "tier": "app", "app": "domain-controller"},
        },
        {
            "vm_id": "hv-vm-3002",
            "name": "SQL-PROD-01",
            "guid": "c8f12a3b-4d5e-6f78-9a01-b2c3d4e5f602",
            "state": "Running",
            "generation": 2,
            "os": {
                "name": "Windows Server",
                "version": "2019 Standard",
                "reference_code": "WIN_SVR_2019_64",
            },
            "cpu": {
                "count": 16,
                "reservation_mhz": 2000,
                "limit_mhz": 100000,
                "relative_weight": 200,
            },
            "memory": {
                "startup_mb": 65536,
                "dynamic_enabled": False,
                "minimum_mb": 65536,
                "maximum_mb": 65536,
                "buffer_percentage": 0,
            },
            "disks": [
                {
                    "name": "SQL-PROD-01-OS.vhdx",
                    "path": "C:\\ClusterStorage\\Vol1\\SQL-PROD-01\\SQL-PROD-01-OS.vhdx",
                    "format": "VHDX",
                    "type": "Dynamic",
                    "max_size_gb": 127,
                    "current_size_gb": 52,
                    "controller": "SCSI Controller 0",
                },
                {
                    "name": "SQL-PROD-01-Data.vhdx",
                    "path": "C:\\ClusterStorage\\Vol2\\SQL-PROD-01\\SQL-PROD-01-Data.vhdx",
                    "format": "VHDX",
                    "type": "Fixed",
                    "max_size_gb": 1024,
                    "current_size_gb": 1024,
                    "controller": "SCSI Controller 1",
                },
                {
                    "name": "SQL-PROD-01-Log.vhdx",
                    "path": "C:\\ClusterStorage\\Vol2\\SQL-PROD-01\\SQL-PROD-01-Log.vhdx",
                    "format": "VHDX",
                    "type": "Fixed",
                    "max_size_gb": 256,
                    "current_size_gb": 256,
                    "controller": "SCSI Controller 1",
                },
                {
                    "name": "SQL-PROD-01-TempDB.vhdx",
                    "path": "C:\\ClusterStorage\\Vol3\\SQL-PROD-01\\SQL-PROD-01-TempDB.vhdx",
                    "format": "VHDX",
                    "type": "Dynamic",
                    "max_size_gb": 128,
                    "current_size_gb": 32,
                    "controller": "SCSI Controller 1",
                },
            ],
            "network_adapters": [
                {
                    "name": "Data-NIC",
                    "switch_name": "vSwitch-Data",
                    "vlan_id": 20,
                    "mac_address": "00:15:5D:02:01:01",
                    "ip_address": "172.16.20.12",
                    "connected": True,
                },
                {
                    "name": "Backup-NIC",
                    "switch_name": "vSwitch-Backup",
                    "vlan_id": 30,
                    "mac_address": "00:15:5D:02:02:01",
                    "ip_address": "172.16.30.12",
                    "connected": True,
                },
            ],
            "checkpoints": [
                {
                    "name": "Pre-CU-Update",
                    "created_at": "2026-03-20T03:00:00Z",
                    "type": "Production",
                    "size_gb": 52.0,
                },
                {
                    "name": "Post-CU-Verified",
                    "created_at": "2026-03-21T10:00:00Z",
                    "type": "Standard",
                    "size_gb": 12.0,
                },
            ],
            "replication": {
                "enabled": True,
                "mode": "Primary",
                "replica_server": "HV-REPLICA-01.corp.local",
                "frequency_seconds": 30,
                "state": "Replicating",
            },
            "cluster": {
                "name": "HV-Cluster-Prod",
                "node": "HV-NODE-02.corp.local",
                "highly_available": True,
            },
            "scvmm": {
                "cloud": "Production-Cloud",
                "service_template": "SQL-HA-Template",
                "custom_properties": {
                    "CostCenter": "DB-OPS-002",
                    "Owner": "database-team",
                    "SQLEdition": "Enterprise",
                },
            },
            "tags": {"env": "production", "tier": "db", "app": "sql-server", "critical": "yes"},
        },
        {
            "vm_id": "hv-vm-3003",
            "name": "WEB-PROD-01",
            "guid": "c8f12a3b-4d5e-6f78-9a01-b2c3d4e5f603",
            "state": "Running",
            "generation": 2,
            "os": {
                "name": "Windows Server",
                "version": "2022 Standard",
                "reference_code": "WIN_SVR_2022_64",
            },
            "cpu": {
                "count": 4,
                "reservation_mhz": 0,
                "limit_mhz": 100000,
                "relative_weight": 100,
            },
            "memory": {
                "startup_mb": 8192,
                "dynamic_enabled": True,
                "minimum_mb": 4096,
                "maximum_mb": 16384,
                "buffer_percentage": 20,
            },
            "disks": [
                {
                    "name": "WEB-PROD-01-OS.vhdx",
                    "path": "C:\\ClusterStorage\\Vol1\\WEB-PROD-01\\WEB-PROD-01-OS.vhdx",
                    "format": "VHDX",
                    "type": "Dynamic",
                    "max_size_gb": 127,
                    "current_size_gb": 38,
                    "controller": "SCSI Controller 0",
                },
                {
                    "name": "WEB-PROD-01-Content.vhdx",
                    "path": "C:\\ClusterStorage\\Vol1\\WEB-PROD-01\\WEB-PROD-01-Content.vhdx",
                    "format": "VHDX",
                    "type": "Dynamic",
                    "max_size_gb": 200,
                    "current_size_gb": 85,
                    "controller": "SCSI Controller 0",
                },
            ],
            "network_adapters": [
                {
                    "name": "Web-NIC",
                    "switch_name": "vSwitch-Corp",
                    "vlan_id": 10,
                    "mac_address": "00:15:5D:03:01:01",
                    "ip_address": "172.16.10.13",
                    "connected": True,
                },
            ],
            "checkpoints": [],
            "replication": {
                "enabled": False,
                "mode": None,
                "replica_server": None,
                "frequency_seconds": None,
                "state": "Disabled",
            },
            "cluster": {
                "name": "HV-Cluster-Prod",
                "node": "HV-NODE-01.corp.local",
                "highly_available": True,
            },
            "scvmm": {
                "cloud": "Production-Cloud",
                "service_template": "IIS-Template-v3",
                "custom_properties": {
                    "CostCenter": "WEB-OPS-003",
                    "Owner": "web-team",
                },
            },
            "tags": {"env": "production", "tier": "web", "app": "iis-webserver"},
        },
        {
            "vm_id": "hv-vm-3004",
            "name": "APP-PROD-01",
            "guid": "c8f12a3b-4d5e-6f78-9a01-b2c3d4e5f604",
            "state": "Running",
            "generation": 1,
            "os": {
                "name": "Windows Server",
                "version": "2016 Standard",
                "reference_code": "WIN_SVR_2016_64",
            },
            "cpu": {
                "count": 8,
                "reservation_mhz": 0,
                "limit_mhz": 100000,
                "relative_weight": 150,
            },
            "memory": {
                "startup_mb": 16384,
                "dynamic_enabled": False,
                "minimum_mb": 16384,
                "maximum_mb": 16384,
                "buffer_percentage": 0,
            },
            "disks": [
                {
                    "name": "APP-PROD-01-OS.vhd",
                    "path": "E:\\VMs\\APP-PROD-01\\APP-PROD-01-OS.vhd",
                    "format": "VHD",
                    "type": "Fixed",
                    "max_size_gb": 80,
                    "current_size_gb": 80,
                    "controller": "IDE Controller 0",
                },
                {
                    "name": "APP-PROD-01-Data.vhdx",
                    "path": "E:\\VMs\\APP-PROD-01\\APP-PROD-01-Data.vhdx",
                    "format": "VHDX",
                    "type": "Dynamic",
                    "max_size_gb": 500,
                    "current_size_gb": 210,
                    "controller": "SCSI Controller 0",
                },
            ],
            "network_adapters": [
                {
                    "name": "App-NIC",
                    "switch_name": "vSwitch-Data",
                    "vlan_id": 20,
                    "mac_address": "00:15:5D:04:01:01",
                    "ip_address": "172.16.20.14",
                    "connected": True,
                },
            ],
            "checkpoints": [
                {
                    "name": "Before-.NET-Upgrade",
                    "created_at": "2026-02-10T08:00:00Z",
                    "type": "Standard",
                    "size_gb": 22.0,
                },
            ],
            "replication": {
                "enabled": False,
                "mode": None,
                "replica_server": None,
                "frequency_seconds": None,
                "state": "Disabled",
            },
            "cluster": {
                "name": None,
                "node": "HV-STANDALONE-01.corp.local",
                "highly_available": False,
            },
            "scvmm": {
                "cloud": "Production-Cloud",
                "service_template": None,
                "custom_properties": {
                    "CostCenter": "APP-OPS-004",
                    "Owner": "app-team",
                    "LegacyApp": "true",
                },
            },
            "tags": {"env": "production", "tier": "app", "app": "legacy-dotnet", "legacy": "yes"},
        },
        {
            "vm_id": "hv-vm-3005",
            "name": "FILE-PROD-01",
            "guid": "c8f12a3b-4d5e-6f78-9a01-b2c3d4e5f605",
            "state": "Running",
            "generation": 2,
            "os": {
                "name": "Windows Server",
                "version": "2022 Standard",
                "reference_code": "WIN_SVR_2022_64",
            },
            "cpu": {
                "count": 4,
                "reservation_mhz": 0,
                "limit_mhz": 100000,
                "relative_weight": 100,
            },
            "memory": {
                "startup_mb": 16384,
                "dynamic_enabled": True,
                "minimum_mb": 8192,
                "maximum_mb": 32768,
                "buffer_percentage": 25,
            },
            "disks": [
                {
                    "name": "FILE-PROD-01-OS.vhdx",
                    "path": "C:\\ClusterStorage\\Vol1\\FILE-PROD-01\\FILE-PROD-01-OS.vhdx",
                    "format": "VHDX",
                    "type": "Dynamic",
                    "max_size_gb": 127,
                    "current_size_gb": 35,
                    "controller": "SCSI Controller 0",
                },
                {
                    "name": "FILE-PROD-01-Shares.vhdx",
                    "path": "C:\\ClusterStorage\\Vol4\\FILE-PROD-01\\FILE-PROD-01-Shares.vhdx",
                    "format": "VHDX",
                    "type": "Fixed",
                    "max_size_gb": 2048,
                    "current_size_gb": 2048,
                    "controller": "SCSI Controller 1",
                },
            ],
            "network_adapters": [
                {
                    "name": "Corp-NIC",
                    "switch_name": "vSwitch-Corp",
                    "vlan_id": 10,
                    "mac_address": "00:15:5D:05:01:01",
                    "ip_address": "172.16.10.15",
                    "connected": True,
                },
                {
                    "name": "Data-NIC",
                    "switch_name": "vSwitch-Data",
                    "vlan_id": 20,
                    "mac_address": "00:15:5D:05:02:01",
                    "ip_address": "172.16.20.15",
                    "connected": True,
                },
            ],
            "checkpoints": [],
            "replication": {
                "enabled": True,
                "mode": "Primary",
                "replica_server": "HV-REPLICA-01.corp.local",
                "frequency_seconds": 900,
                "state": "Replicating",
            },
            "cluster": {
                "name": "HV-Cluster-Prod",
                "node": "HV-NODE-02.corp.local",
                "highly_available": True,
            },
            "scvmm": {
                "cloud": "Production-Cloud",
                "service_template": "FileServer-Template",
                "custom_properties": {
                    "CostCenter": "INFRA-005",
                    "Owner": "storage-team",
                },
            },
            "tags": {"env": "production", "tier": "data", "app": "file-server"},
        },
    ],
    "virtual_switches": [
        {
            "name": "vSwitch-Corp",
            "type": "External",
            "switch_type": "Logical",
            "bandwidth_mode": "Weight",
            "description": "Corporate LAN access",
            "vlan_id": 10,
            "subnet": "172.16.10.0/24",
            "gateway": "172.16.10.1",
            "connected_adapters": 3,
            "host": "HV-NODE-01.corp.local",
        },
        {
            "name": "vSwitch-Data",
            "type": "External",
            "switch_type": "Logical",
            "bandwidth_mode": "Weight",
            "description": "Database and application data VLAN",
            "vlan_id": 20,
            "subnet": "172.16.20.0/24",
            "gateway": "172.16.20.1",
            "connected_adapters": 4,
            "host": "HV-NODE-02.corp.local",
        },
        {
            "name": "vSwitch-Backup",
            "type": "External",
            "switch_type": "Standard",
            "bandwidth_mode": "None",
            "description": "Backup and replication network",
            "vlan_id": 30,
            "subnet": "172.16.30.0/24",
            "gateway": "172.16.30.1",
            "connected_adapters": 1,
            "host": "HV-NODE-02.corp.local",
        },
    ],
    "firewalls": [
        {
            "id": "fw-hv-01",
            "name": "hyperv-windows-fw",
            "rules": [
                {
                    "order": 1,
                    "action": "permit",
                    "protocol": "tcp",
                    "source": "0.0.0.0/0",
                    "destination": "172.16.10.0/24",
                    "port": 443,
                    "description": "Allow HTTPS to corporate VLAN",
                },
                {
                    "order": 2,
                    "action": "permit",
                    "protocol": "tcp",
                    "source": "172.16.10.0/24",
                    "destination": "172.16.20.0/24",
                    "port": 1433,
                    "description": "Allow SQL Server from corp to data VLAN",
                },
                {
                    "order": 3,
                    "action": "permit",
                    "protocol": "tcp",
                    "source": "172.16.20.0/24",
                    "destination": "172.16.30.0/24",
                    "port_range": "8000-9000",
                    "description": "Allow backup agents",
                },
                {
                    "order": 4,
                    "action": "permit",
                    "protocol": "tcp",
                    "source": "172.16.10.0/24",
                    "destination": "172.16.10.0/24",
                    "port": 445,
                    "description": "Allow SMB file sharing within corp VLAN",
                },
                {
                    "order": 5,
                    "action": "deny",
                    "protocol": "all",
                    "source": "0.0.0.0/0",
                    "destination": "172.16.30.0/24",
                    "port": None,
                    "description": "Deny all external to backup VLAN",
                },
            ],
        },
    ],
}
