"""Realistic mock data simulating bare metal server fleet management API responses.

Complex fleet: 5 servers with RAID arrays, dual-NIC bonding, GPU node,
UEFI/legacy BIOS, IPMI/BMC metadata.
"""

BARE_METAL_MOCK_DATA: dict = {
    "servers": [
        {
            "server_id": "bm-2001",
            "hostname": "db-primary-bm01",
            "serial_number": "SN-4829103-A",
            "manufacturer": "Dell",
            "model": "PowerEdge R740xd",
            "bios": {
                "type": "UEFI",
                "version": "2.14.0",
                "secure_boot": True,
            },
            "bmc": {
                "ip_address": "10.50.0.11",
                "type": "iDRAC9",
                "firmware_version": "6.10.30.00",
                "username": "root",
            },
            "cpu": {
                "sockets": 2,
                "cores_per_socket": 16,
                "total_cores": 32,
                "model": "Intel Xeon Gold 6226R",
                "architecture": "x86_64",
                "threads_per_core": 2,
            },
            "memory_gb": 256,
            "os": {
                "name": "Red Hat Enterprise Linux",
                "version": "8.8",
                "kernel": "4.18.0-477.27.1.el8_8.x86_64",
                "reference_code": "RHEL_8_64",
            },
            "storage": {
                "controller": "PERC H740P",
                "disks": [
                    {
                        "slot": 0,
                        "type": "SSD",
                        "capacity_gb": 480,
                        "model": "Samsung PM893",
                        "interface": "SATA",
                    },
                    {
                        "slot": 1,
                        "type": "SSD",
                        "capacity_gb": 480,
                        "model": "Samsung PM893",
                        "interface": "SATA",
                    },
                    {
                        "slot": 2,
                        "type": "NVMe",
                        "capacity_gb": 3840,
                        "model": "Samsung PM9A3",
                        "interface": "PCIe",
                    },
                    {
                        "slot": 3,
                        "type": "NVMe",
                        "capacity_gb": 3840,
                        "model": "Samsung PM9A3",
                        "interface": "PCIe",
                    },
                ],
                "raid_arrays": [
                    {
                        "name": "VD-BOOT",
                        "level": "RAID1",
                        "disks": [0, 1],
                        "size_gb": 480,
                        "mount_point": "/",
                        "state": "Optimal",
                    },
                    {
                        "name": "VD-DATA",
                        "level": "RAID0",
                        "disks": [2, 3],
                        "size_gb": 7680,
                        "mount_point": "/data",
                        "state": "Optimal",
                    },
                ],
            },
            "network": {
                "interfaces": [
                    {
                        "name": "bond0",
                        "type": "bond",
                        "mode": "802.3ad",
                        "slaves": ["eno1", "eno2"],
                        "ip_address": "10.100.10.11",
                        "netmask": "255.255.255.0",
                        "mac_address": "AA:BB:CC:01:01:01",
                        "speed_gbps": 20,
                        "vlan_id": 100,
                    },
                    {
                        "name": "bond1",
                        "type": "bond",
                        "mode": "active-backup",
                        "slaves": ["eno3", "eno4"],
                        "ip_address": "10.100.20.11",
                        "netmask": "255.255.255.0",
                        "mac_address": "AA:BB:CC:01:02:01",
                        "speed_gbps": 20,
                        "vlan_id": 200,
                    },
                ],
            },
            "gpu": None,
            "power_state": "on",
            "location": {
                "datacenter": "DC-East",
                "rack": "R-12",
                "unit": "U22-U25",
            },
            "tags": ["env:production", "tier:db", "app:postgresql", "critical:yes"],
        },
        {
            "server_id": "bm-2002",
            "hostname": "app-compute-bm01",
            "serial_number": "SN-4829104-B",
            "manufacturer": "Dell",
            "model": "PowerEdge R750",
            "bios": {
                "type": "UEFI",
                "version": "1.8.2",
                "secure_boot": True,
            },
            "bmc": {
                "ip_address": "10.50.0.12",
                "type": "iDRAC9",
                "firmware_version": "6.10.30.00",
                "username": "root",
            },
            "cpu": {
                "sockets": 2,
                "cores_per_socket": 24,
                "total_cores": 48,
                "model": "Intel Xeon Gold 6342",
                "architecture": "x86_64",
                "threads_per_core": 2,
            },
            "memory_gb": 512,
            "os": {
                "name": "Ubuntu",
                "version": "22.04",
                "kernel": "5.15.0-91-generic",
                "reference_code": "UBUNTU_22_04_64",
            },
            "storage": {
                "controller": "PERC H755",
                "disks": [
                    {
                        "slot": 0,
                        "type": "SSD",
                        "capacity_gb": 960,
                        "model": "Micron 5400 PRO",
                        "interface": "SATA",
                    },
                    {
                        "slot": 1,
                        "type": "SSD",
                        "capacity_gb": 960,
                        "model": "Micron 5400 PRO",
                        "interface": "SATA",
                    },
                    {
                        "slot": 2,
                        "type": "SSD",
                        "capacity_gb": 960,
                        "model": "Micron 5400 PRO",
                        "interface": "SATA",
                    },
                ],
                "raid_arrays": [
                    {
                        "name": "VD-SYSTEM",
                        "level": "RAID5",
                        "disks": [0, 1, 2],
                        "size_gb": 1920,
                        "mount_point": "/",
                        "state": "Optimal",
                    },
                ],
            },
            "network": {
                "interfaces": [
                    {
                        "name": "bond0",
                        "type": "bond",
                        "mode": "802.3ad",
                        "slaves": ["eno1", "eno2"],
                        "ip_address": "10.100.20.12",
                        "netmask": "255.255.255.0",
                        "mac_address": "AA:BB:CC:02:01:01",
                        "speed_gbps": 25,
                        "vlan_id": 200,
                    },
                ],
            },
            "gpu": None,
            "power_state": "on",
            "location": {
                "datacenter": "DC-East",
                "rack": "R-12",
                "unit": "U18-U19",
            },
            "tags": ["env:production", "tier:app", "app:compute-cluster"],
        },
        {
            "server_id": "bm-2003",
            "hostname": "gpu-ml-bm01",
            "serial_number": "SN-4829105-C",
            "manufacturer": "Dell",
            "model": "PowerEdge R750xa",
            "bios": {
                "type": "UEFI",
                "version": "1.8.2",
                "secure_boot": False,
            },
            "bmc": {
                "ip_address": "10.50.0.13",
                "type": "iDRAC9",
                "firmware_version": "6.10.30.00",
                "username": "root",
            },
            "cpu": {
                "sockets": 2,
                "cores_per_socket": 16,
                "total_cores": 32,
                "model": "Intel Xeon Gold 6326",
                "architecture": "x86_64",
                "threads_per_core": 2,
            },
            "memory_gb": 256,
            "os": {
                "name": "Ubuntu",
                "version": "22.04",
                "kernel": "5.15.0-91-generic",
                "reference_code": "UBUNTU_22_04_64",
            },
            "storage": {
                "controller": "PERC H755",
                "disks": [
                    {
                        "slot": 0,
                        "type": "NVMe",
                        "capacity_gb": 1920,
                        "model": "Samsung PM9A3",
                        "interface": "PCIe",
                    },
                    {
                        "slot": 1,
                        "type": "NVMe",
                        "capacity_gb": 1920,
                        "model": "Samsung PM9A3",
                        "interface": "PCIe",
                    },
                ],
                "raid_arrays": [
                    {
                        "name": "VD-ALL",
                        "level": "RAID1",
                        "disks": [0, 1],
                        "size_gb": 1920,
                        "mount_point": "/",
                        "state": "Optimal",
                    },
                ],
            },
            "network": {
                "interfaces": [
                    {
                        "name": "bond0",
                        "type": "bond",
                        "mode": "802.3ad",
                        "slaves": ["eno1", "eno2"],
                        "ip_address": "10.100.30.13",
                        "netmask": "255.255.255.0",
                        "mac_address": "AA:BB:CC:03:01:01",
                        "speed_gbps": 100,
                        "vlan_id": 300,
                    },
                ],
            },
            "gpu": {
                "count": 4,
                "model": "NVIDIA A100 80GB",
                "memory_gb": 80,
                "driver_version": "535.129.03",
                "cuda_version": "12.2",
            },
            "power_state": "on",
            "location": {
                "datacenter": "DC-East",
                "rack": "R-14",
                "unit": "U30-U33",
            },
            "tags": ["env:production", "tier:compute", "app:ml-training", "gpu:yes"],
        },
        {
            "server_id": "bm-2004",
            "hostname": "legacy-erp-bm01",
            "serial_number": "SN-3918201-D",
            "manufacturer": "IBM",
            "model": "Power System S922",
            "bios": {
                "type": "OPAL",
                "version": "FW940.30",
                "secure_boot": False,
            },
            "bmc": {
                "ip_address": "10.50.0.14",
                "type": "HMC",
                "firmware_version": "V10R1M1010",
                "username": "hscroot",
            },
            "cpu": {
                "sockets": 2,
                "cores_per_socket": 10,
                "total_cores": 20,
                "model": "POWER9",
                "architecture": "ppc64le",
                "threads_per_core": 4,
            },
            "memory_gb": 128,
            "os": {
                "name": "AIX",
                "version": "7.3",
                "kernel": "7300-01-01-2341",
                "reference_code": "AIX_7_3",
            },
            "storage": {
                "controller": "SAS RAID",
                "disks": [
                    {
                        "slot": 0,
                        "type": "SAS",
                        "capacity_gb": 600,
                        "model": "IBM ESDA",
                        "interface": "SAS",
                    },
                    {
                        "slot": 1,
                        "type": "SAS",
                        "capacity_gb": 600,
                        "model": "IBM ESDA",
                        "interface": "SAS",
                    },
                    {
                        "slot": 2,
                        "type": "SAS",
                        "capacity_gb": 600,
                        "model": "IBM ESDA",
                        "interface": "SAS",
                    },
                    {
                        "slot": 3,
                        "type": "SAS",
                        "capacity_gb": 600,
                        "model": "IBM ESDA",
                        "interface": "SAS",
                    },
                ],
                "raid_arrays": [
                    {
                        "name": "hdisk0",
                        "level": "RAID1",
                        "disks": [0, 1],
                        "size_gb": 600,
                        "mount_point": "/",
                        "state": "Optimal",
                    },
                    {
                        "name": "hdisk1",
                        "level": "RAID1",
                        "disks": [2, 3],
                        "size_gb": 600,
                        "mount_point": "/data",
                        "state": "Optimal",
                    },
                ],
            },
            "network": {
                "interfaces": [
                    {
                        "name": "en0",
                        "type": "ethernet",
                        "mode": None,
                        "slaves": [],
                        "ip_address": "10.100.10.14",
                        "netmask": "255.255.255.0",
                        "mac_address": "AA:BB:CC:04:01:01",
                        "speed_gbps": 10,
                        "vlan_id": 100,
                    },
                ],
            },
            "gpu": None,
            "power_state": "on",
            "location": {
                "datacenter": "DC-East",
                "rack": "R-08",
                "unit": "U10-U13",
            },
            "tags": ["env:production", "tier:app", "app:erp-sap", "legacy:yes"],
        },
        {
            "server_id": "bm-2005",
            "hostname": "web-edge-bm01",
            "serial_number": "SN-4829106-E",
            "manufacturer": "HPE",
            "model": "ProLiant DL380 Gen10 Plus",
            "bios": {
                "type": "Legacy",
                "version": "U46 v2.72",
                "secure_boot": False,
            },
            "bmc": {
                "ip_address": "10.50.0.15",
                "type": "iLO5",
                "firmware_version": "2.81",
                "username": "Administrator",
            },
            "cpu": {
                "sockets": 1,
                "cores_per_socket": 8,
                "total_cores": 8,
                "model": "Intel Xeon Silver 4215R",
                "architecture": "x86_64",
                "threads_per_core": 2,
            },
            "memory_gb": 64,
            "os": {
                "name": "CentOS",
                "version": "7.9",
                "kernel": "3.10.0-1160.105.1.el7.x86_64",
                "reference_code": "CENTOS_7_64",
            },
            "storage": {
                "controller": "Smart Array P408i-a",
                "disks": [
                    {
                        "slot": 0,
                        "type": "SSD",
                        "capacity_gb": 480,
                        "model": "HPE VK000480GWSRR",
                        "interface": "SATA",
                    },
                ],
                "raid_arrays": [
                    {
                        "name": "LD-0",
                        "level": "NONE",
                        "disks": [0],
                        "size_gb": 480,
                        "mount_point": "/",
                        "state": "Optimal",
                    },
                ],
            },
            "network": {
                "interfaces": [
                    {
                        "name": "eno1",
                        "type": "ethernet",
                        "mode": None,
                        "slaves": [],
                        "ip_address": "10.100.10.15",
                        "netmask": "255.255.255.0",
                        "mac_address": "AA:BB:CC:05:01:01",
                        "speed_gbps": 10,
                        "vlan_id": 100,
                    },
                ],
            },
            "gpu": None,
            "power_state": "on",
            "location": {
                "datacenter": "DC-East",
                "rack": "R-04",
                "unit": "U05-U06",
            },
            "tags": ["env:production", "tier:web", "app:nginx-lb"],
        },
    ],
    "networks": [
        {
            "vlan_id": 100,
            "name": "bm-mgmt-db",
            "cidr": "10.100.10.0/24",
            "gateway": "10.100.10.1",
            "zone": "restricted",
            "description": "Management and database VLAN",
        },
        {
            "vlan_id": 200,
            "name": "bm-app",
            "cidr": "10.100.20.0/24",
            "gateway": "10.100.20.1",
            "zone": "trusted",
            "description": "Application tier VLAN",
        },
        {
            "vlan_id": 300,
            "name": "bm-gpu-compute",
            "cidr": "10.100.30.0/24",
            "gateway": "10.100.30.1",
            "zone": "trusted",
            "description": "GPU compute / ML training VLAN",
        },
    ],
    "firewalls": [
        {
            "id": "fw-bm-01",
            "name": "bm-perimeter-fw",
            "rules": [
                {
                    "order": 1,
                    "action": "permit",
                    "protocol": "tcp",
                    "source": "0.0.0.0/0",
                    "destination": "10.100.10.0/24",
                    "port": 443,
                    "description": "Allow HTTPS to management VLAN",
                },
                {
                    "order": 2,
                    "action": "permit",
                    "protocol": "tcp",
                    "source": "10.100.20.0/24",
                    "destination": "10.100.10.0/24",
                    "port": 5432,
                    "description": "Allow PostgreSQL from app to db",
                },
                {
                    "order": 3,
                    "action": "permit",
                    "protocol": "tcp",
                    "source": "10.100.10.0/24",
                    "destination": "10.100.20.0/24",
                    "port_range": "8080-8443",
                    "description": "Allow app tier HTTP services",
                },
                {
                    "order": 4,
                    "action": "deny",
                    "protocol": "all",
                    "source": "0.0.0.0/0",
                    "destination": "10.100.30.0/24",
                    "port": None,
                    "description": "Deny all external to GPU VLAN",
                },
            ],
        },
    ],
}
